# Generated by Django 4.1 on 2022-08-27 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quesmodel',
            old_name='ans',
            new_name='op5',
        ),
    ]
